### PR TITLE
Improve default sorting

### PR DESCRIPTION
**Pull request by quangkhoa**

### CODE REVIEW

**Comment by brendo** [comment]
Is this in preparation for #16?

**Comment by quangkhoa** [comment]
Not really. The current sorting behaviour is buggy and not in any logical order, e.g. for `Account`
- GET 'Get list of registered account'
- POST 'Register client account configuration data'
- GET 'Get account configuration data of a given account'

With this fix, the methods are sorted by http method type first, then by description.

**Comment by brendo** [comment]
The sorting change looks fine. The change from `summary` to `title` is incomplete (check the tests). Also needs a rebase :)

**Comment by quangkhoa** [comment]
Thanks Brendan. I've fixed the tests and also did a rebase.

**Pull request merged**
