### PR TITLE
adding path to navigation

### PR DESCRIPTION
**Pull request by Szasza**
Addressing #199.

### CODE REVIEW

**Review by brendo — APPROVED** [review]

**Comment by Szasza** [comment]
@brendo thank you for the review. Could it be merged and maybe released if there isn't anything else pending?

**Comment by brendo** [comment]
Trying to get #201 with this, but if we're unable to resolve today this will be merged and released (as 0.3.0)

**Comment by Szasza** [comment]
Sounds great, thank you for the info.

**Comment by Szasza** [comment]
Thank you for the merge, and the version bump, much appreciated :)

**Pull request merged**
